version: "3.8"

services:
  backend:
    image: git.mootfrost.dev/mootfrost777/windmill-ai_backend:latest
    container_name: windmill-ai-backend
    restart: always
    build: backend/
  frontend:
    image: git.mootfrost.dev/mootfrost777/windmill-ai_frontend:latest
    container_name: windmill-ai-frontend
    restart: always
    build: frontend/
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.windmill_ai.rule=Host(`windmill.mootfrost.dev`)
    # Website port
    ports:
      - "7655:80"
