version: "3.8"

services:
  backend:
    image: git.mootfrost.dev/mootfrost777/windmill-ai_backend:latest
    container_name: windmill-ai-backend
    restart: always
    volumes:
      - static_data:/data/static
    environment:
      - DB_URL=postgresql+asyncpg://postgres:owl@db:5432/windmill
    build: backend/
    expose:
      - 7632
  frontend:
    image: git.mootfrost.dev/mootfrost777/windmill-ai_frontend:latest
    container_name: windmill-ai-frontend
    restart: always
    build: frontend/
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.windmill_ai.rule=Host(`windmill.mootfrost.dev`)
    # Website port
    ports:
      - "7655:80"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=owl
      - POSTGRES_DB=windmill
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  db_data:
  static_data:
