name: deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: build
        run: docker compose build
      -
        name: up
        run: docker compose up -d
      -
        name: prune
        run: docker image prune