"""add defect types

Revision ID: 28d9cf7d6cc6
Revises: 9886559a148e
Create Date: 2024-07-11 11:46:59.158145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d9cf7d6cc6'
down_revision: Union[str, None] = '9886559a148e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defects', sa.Column('type_id', sa.Integer(), nullable=False))
    op.drop_column('defects', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defects', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('defects', 'type_id')
    # ### end Alembic commands ###
