"""change type to name in defect_types

Revision ID: aa85c46135a9
Revises: 04de0e0f2aba
Create Date: 2024-07-14 10:17:23.982367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa85c46135a9'
down_revision: Union[str, None] = '04de0e0f2aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect_types', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('defect_types', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect_types', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('defect_types', 'name')
    # ### end Alembic commands ###
