"""add yolo defects

Revision ID: f653fd7f4ec8
Revises: 9c0b5149c1c0
Create Date: 2024-07-10 08:37:14.002967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f653fd7f4ec8'
down_revision: Union[str, None] = '9c0b5149c1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defects', sa.Column('type', sa.String(), nullable=False))
    op.add_column('defects', sa.Column('coordinates', sa.String(), nullable=False))
    op.add_column('defects', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('defects', sa.Column('image_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'defects', 'scan_results', ['image_id'], ['id'])
    op.drop_column('defects', 'name')
    op.drop_column('defects', 'color')
    op.drop_constraint('scan_results_defect_id_fkey', 'scan_results', type_='foreignkey')
    op.drop_column('scan_results', 'defect_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_results', sa.Column('defect_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('scan_results_defect_id_fkey', 'scan_results', 'defects', ['defect_id'], ['id'])
    op.add_column('defects', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('defects', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'defects', type_='foreignkey')
    op.drop_column('defects', 'image_id')
    op.drop_column('defects', 'confidence')
    op.drop_column('defects', 'coordinates')
    op.drop_column('defects', 'type')
    # ### end Alembic commands ###
