"""add defect types relation

Revision ID: cdacaed6987c
Revises: 28d9cf7d6cc6
Create Date: 2024-07-11 11:50:24.845823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdacaed6987c'
down_revision: Union[str, None] = '28d9cf7d6cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'defects', 'defect_types', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'defects', type_='foreignkey')
    op.drop_table('defect_types')
    # ### end Alembic commands ###
