"""add color to defect_types

Revision ID: 04de0e0f2aba
Revises: 861fb019ecd0
Create Date: 2024-07-14 10:12:53.385972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04de0e0f2aba'
down_revision: Union[str, None] = '861fb019ecd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect_types', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defect_types', 'color')
    # ### end Alembic commands ###
