"""fix relation

Revision ID: 9c0b5149c1c0
Revises: 4239575e2384
Create Date: 2024-07-08 15:34:47.227086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0b5149c1c0'
down_revision: Union[str, None] = '4239575e2384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_results', sa.Column('defect_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'scan_results', 'defects', ['defect_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_results', type_='foreignkey')
    op.drop_column('scan_results', 'defect_id')
    # ### end Alembic commands ###
